platform :ios, '9.0'

inhibit_all_warnings!


source 'https://github.com/CocoaPods/Specs.git'


install! 'cocoapods',
:deterministic_uuids => false,
generate_multiple_pod_projects: true


#brew install git-lfs
#git lfs install
#pod update

target 'CrashDemo' do  
end
